model:
    augmentations: [ "affine","blur"]
    target_augmentations: ["intensity"]
    val_augmentations: "none"
    aug_prob: 0.5
    lr: 0.0001
    target_tau: 0

    encoder_model_name: conv2d
    encoder_dict:
        in_channels: 9
        channels: [32,64,64]
        kernel_sizes: [3,3,3]

    dynamics_dict:
        num_heads: 2
        mlp_dim: 128
        num_attention_layers: 2
        action_dim: -1
        in_features: -1
        num_patches: -1
    device: "cpu"

env:
    num_transitions: 50000
    num_sprites: 2
    all_sprite_mover: True
    random_init_places: False

train_loop:
    batch_size: 64
    num_epochs: 50
    num_workers: 2

hydra:
    run:
        dir: outputs/patch_contrastive/${now:%Y.%m.%d}/${now:%H%M%S}/
    sweep:
        dir: ./${algorithm.name}/${experiment}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}
