defaults:
    - encoder_decoder: vae
    - dynamics: attention_dynamics
    - env: spriteworld

num_workers: 1
encoder_decoder_path : -1

dynamics_model_path : "/cluster/home/gboeshertz/patch_rl/outputs/dynamics/patch_vae/2023.01.18/190530/best_val_dynamics.pt"
test_data_path:  "/cluster/home/gboeshertz/patch_rl/data/expert_visual_5000transitions_4_all_sprite_mover_True_4instantmoveno_targets.npz"

loss_weights:
    dyn_loss_weight: 0
    vae_loss_weight: 1 
    inverse_loss_weight: 0

env:
  num_transitions: 10000
  num_action_repeat: 4


hydra:
    run:
        dir: outputs/test_dynamics/${encoder_decoder.name}/${now:%Y.%m.%d}/${now:%H%M%S}/
