defaults:
    - encoder_decoder: vae
    - dynamics: attention_dynamics

device: "cpu"
num_workers: 1
encoder_decoder_path : -1

dynamics_model_path : "/cluster/home/gboeshertz/patch_rl/outputs/dynamics/patch_vae/2022.11.26/152300/best_val_dynamics.pt"

loss_weights:
    dyn_loss_weight: 0
    vae_loss_weight: 1 
    inverse_loss_weight: 0

env:
    num_transitions: 10000
    num_sprites: 4
    all_sprite_mover: True
    one_sprite_mover: False
    discrete_all_sprite_mover: False
    random_init_places: False
    num_action_repeat: 2
    instant_move: True
    dont_show_targets: True


hydra:
    run:
        dir: outputs/test_dynamics/${encoder_decoder.name}/${now:%Y.%m.%d}/${now:%H%M%S}/
