defaults:
    - model: vqvae_model
env:
    num_transitions: 10000
    num_sprites: 4
    all_sprite_mover: False
    one_sprite_mover: False
    discrete_all_sprite_mover: True
    random_init_places: True
    num_action_repeat: 4
    instant_move: False
    
train_loop:
    batch_size: 8
    num_epochs: 200
    num_workers: 3
    lr: 0.0001

hydra:
    run:
        dir: outputs/vqvae/${now:%Y.%m.%d}/${now:%H%M%S}/
    sweep:
        dir: ./${algorithm.name}/${experiment}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}
