defaults:
    - dynamics: attention_dynamics
    - encoder_decoder: vae

device: "cpu"                                               
encoder_decoder_path : "/cluster/home/gboeshertz/patch_rl/outputs/patch_model/patch_vae/2022.11.25/153213/best_val_encoder_decoder.pt"
recons_loss: False

env:
    num_transitions: 150
    num_sprites: 4
    all_sprite_mover: True
    one_sprite_mover: False
    discrete_all_sprite_mover: False
    random_init_places: True
    num_action_repeat: 4
    instant_move: True
    dont_show_targets: True

    
train_loop:
    batch_size: 3
    num_epochs: 300
    num_workers: 1
    lr: 0.0005
    scheduler_milestones: [200,250]


hydra:
    run:
        dir: outputs/dynamics/${encoder_decoder.name}/${now:%Y.%m.%d}/${now:%H%M%S}/
