defaults:
    - dynamics: attention_dynamics
    - encoder_decoder: vae

device: "cpu"
encoder_decoder_path : "/cluster/home/gboeshertz/patch_rl/outputs/patch_model/patch_vae/2022.11.08/210639/best_val_encoder_decoder.pt"
recons_loss: True

env:
    num_transitions: 150
    num_sprites: 4
    all_sprite_mover: False
    one_sprite_mover: False
    discrete_all_sprite_mover: True
    random_init_places: True
    num_action_repeat: 4
    instant_move: False
    
train_loop:
    batch_size: 32
    num_epochs: 200
    num_workers: 3
    lr: 0.0005
    scheduler_milestones: [100,150]


hydra:
    run:
        dir: outputs/dynamics/${encoder_decoder.name}/${now:%Y.%m.%d}/${now:%H%M%S}/
