defaults:
    - model: patch_vae_model
env:
    num_transitions: 50000
    num_sprites: 4
    all_sprite_mover: True
    random_init_places: True
    num_action_repeat: 4
    instant_move: True


train_loop:
    batch_size: 16
    num_epochs: 50
    num_workers: 3
    lr: 0.0001

hydra:
    run:
        dir: outputs/patch_reconstruction/${now:%Y.%m.%d}/${now:%H%M%S}/
    sweep:
        dir: ./${algorithm.name}/${experiment}/${overrides.env}/${now:%Y.%m.%d}/${now:%H%M%S}
