defaults:
    - encoder_decoder: vae
    - dynamics: attention_dynamics
    - inverse: cnn

device: "cpu"

loss_weights:
    dyn_loss_weight: 1
    vae_loss_weight: 1 
    inverse_loss_weight: 0

env:
    num_transitions: 150
    num_sprites: 4
    all_sprite_mover: False
    one_sprite_mover: False
    discrete_all_sprite_mover: True
    random_init_places: True
    num_action_repeat: 4
    instant_move: False
    
train_loop:
    batch_size: 2
    num_epochs: 200
    num_workers: 3
    lr: 0.0001

hydra:
    run:
        dir: outputs/patch_model/${encoder_decoder.name}/${now:%Y.%m.%d}/${now:%H%M%S}/
