_target_: src.inverse_dynamics_model.PatchInverseDynamicsModel
encoder:
    in_channels: -1
    channels: [128,64,32,16]
    kernel_sizes: [3,3,3,3]
    strides: [1,1,1,1]
    paddings: [1,1,1,1]
    dropout: 0.2
    norm_type: bn
    use_maxpool: False
mlp:
    input_size: -1
    layer_sizes : [256,128,64]
    output_size: -1