
_target_: src.patch_vae.PatchVAE
patch_size: 32
in_channels: 9
latent_dim: 256
channels: [64,64,128,256]
kernel_sizes: [3,3,3,3]
paddings: [1,1,1,1]
strides: [2,3,2,2]
kld_weight: 0.001
loss_type: 'B'
gamma: 10.0
max_capacity: 25
Capacity_max_iter: 10000
beta: 4
