name: mlppatch_vae
_target_: src.small_patch_vae.MLPPatchVAE
patch_size: 4
in_channels: 3
embed_dim: 10
channels: [64,32,16] #[64,64,128,256]
kld_weight: 0.001
loss_type: 'B'
gamma: 30.0
max_capacity: 30
Capacity_max_iter: 500000
beta: 4
norm_type: gn
