name: patch_swae
_target_: src.patch_swae.PatchSWAE
patch_size: 16
in_channels: 3
embed_dim: 256
channels: [64,128,256] #[64,64,128,256]
kernel_sizes: [3,3,3] #[3,3,3,3]
paddings: [1,1,1]
strides: [2,2,2] #[2,3,2,2]
norm_type: gn
reg_weight: 100
wasserstein_deg: 2.
num_projections: 50
projection_dist: normal
