name: "vqvae"
_target_: src.vqvae.VQVAE
vocab_size: 512
embed_dim: 512
in_channels: 3
encoder:
    resolution: 64
    in_channels: 3
    z_channels: 512
    ch: 64
    ch_mult: [1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
    resolution: -1
    in_channels: -1
    z_channels: -1
    ch: -1
    ch_mult: -1
    num_res_blocks: -1
    attn_resolutions: -1
    out_ch: -1
    dropout: -1

