_target_: src.dynamics_model.AttentionDynamicsModel
num_heads: 8
mlp_dim: 1028
num_attention_layers: 1
dropout: 0.2
action_dim: 4
in_features: -1
num_patches: -1
group_actions: False
residual: True
use_attn_mask: False
discrete_actions: True
regularizer_weight: 0.1
num_actions: -1
embed_dim: 1028
same_action_prediction: False
device: cpu
use_gt_mask: False
action_regularization: False