defaults:
    - patch_vae: 2d

augmentations: [ "blur","color","noise"]
aug_prob: 0.5
device: "cpu"
dyn_loss_weight: 1
vae_loss_weight: 1 
dyn_regularizer_weight: 0.1
#patch_vae:
#    patch_size: 32
#    in_channels: 9
#    latent_dim: 256
#    channels: [64,64,128,256]
#    kernel_sizes: [3,3,3,3]
#    paddings: [1,1,1,1]
#    strides: [2,3,2,2]
#    kld_weight: 0.001
#    loss_type: 'B'
#    gamma: 10.0
#    max_capacity: 25
#    Capacity_max_iter: 10000
#    beta: 4

dynamics:
    _target_: src.dynamics_model.AttentionDynamicsModel
    num_heads: 2
    mlp_dim: 256
    num_attention_layers: 2
    dropout: 0.2
    action_dim: -1
    in_features: -1
    num_patches: -1
    group_actions: True
    residual: True
    use_attn_mask: True
