augmentations: [ "blur","color","noise"]
target_augmentations: ["sharp","noise"]
val_augmentations: "none"
aug_prob: 0.5
target_tau: 0.99
device: "cpu"
dyn_loss_weight: 1
byol_loss_weight: 0

patchmaker:
    patch_size: 32
    encoder:
        _target_: src.networks.cnns.Conv2dModel
        in_channels: 9
        channels: [64,64,128,128,256]
        kernel_sizes: [2,3,4,3,2]
        paddings: [1,1,1,1,0]
        strides: [1,3,3,2,2]
        dropout: 0.2
        norm_type: bn    
        use_maxpool: False

patch_decoder:
    patch_size: 32
    decoder:
        _target_: src.networks.cnns.VAE_Decoder
        channels: [256,128,64,64]
        kernel_sizes: [3,3,3,3]
        paddings: [1,1,1,1]
        strides: [2,2,3,2]
        out_dim: 9

dynamics:
    _target_: src.dynamics_model.AttentionDynamicsModel
    num_heads: 2
    mlp_dim: 128
    num_attention_layers: 2
    dropout: 0.2
    action_dim: -1
    in_features: -1
    num_patches: -1
    group_actions: True
    residual: False
